version: "3.9"

services:
  db:
    image: ankane/pgvector:latest
    container_name: rag_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag_keywords
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
